"""
Authentication endpoints.

POST /auth/login                    – Email + password → access token.
GET  /auth/me                       – Current user info.
PUT  /auth/me/password              – Change own password.
POST /auth/reset-password/confirm   – Set new password using a reset token.
"""

from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from pydantic import BaseModel, ConfigDict, EmailStr, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.dependencies import (
    create_access_token,
    get_accessible_databases,
    get_auth_db,
    get_current_user,
    hash_password,
    verify_password,
)
from app.models.user import PasswordResetToken, User

router = APIRouter(prefix="/auth", tags=["auth"])


# ── Response schemas ───────────────────────────────────────────────────────

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user_id: int
    email: str
    full_name: str | None
    is_admin: bool
    must_change_pw: bool
    # List of country databases this user can access, e.g. [{db_name, label}]
    accessible_databases: list[dict]


class UserOut(BaseModel):
    id: int
    email: str
    full_name: str | None
    is_admin: bool
    is_active: bool
    must_change_pw: bool
    created_at: str
    last_login_at: str | None
    # List of country databases this user can access, e.g. [{db_name, label}]
    accessible_databases: list[dict]

    model_config = ConfigDict(from_attributes=True)


class ChangePasswordRequest(BaseModel):
    current_password: str
    new_password: str = Field(..., min_length=8)


class ResetPasswordConfirmRequest(BaseModel):
    token: str
    new_password: str = Field(..., min_length=8)


# ── Endpoints ──────────────────────────────────────────────────────────────

@router.post("/login", response_model=TokenResponse)
async def login(
    form: OAuth2PasswordRequestForm = Depends(),
    db: AsyncSession = Depends(get_auth_db),
):
    """Authenticate with email and password, return a JWT access token."""
    result = await db.execute(select(User).where(User.email == form.username))
    user = result.scalar_one_or_none()

    if not user or not verify_password(form.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if not user.is_active:
        raise HTTPException(status_code=403, detail="Account disabled")

    user.last_login_at = datetime.now(timezone.utc)
    await db.commit()

    accessible_dbs = await get_accessible_databases(user, db)
    token = create_access_token(user.id, user.email)
    return TokenResponse(
        access_token=token,
        user_id=user.id,
        email=user.email,
        full_name=user.full_name,
        is_admin=user.is_admin,
        must_change_pw=user.must_change_pw,
        accessible_databases=accessible_dbs,
    )


@router.get("/me", response_model=UserOut)
async def get_me(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_auth_db),
):
    """Return the currently authenticated user's profile."""
    accessible_dbs = await get_accessible_databases(current_user, db)
    return UserOut(
        id=current_user.id,
        email=current_user.email,
        full_name=current_user.full_name,
        is_admin=current_user.is_admin,
        is_active=current_user.is_active,
        must_change_pw=current_user.must_change_pw,
        created_at=current_user.created_at.isoformat(),
        last_login_at=current_user.last_login_at.isoformat() if current_user.last_login_at else None,
        accessible_databases=accessible_dbs,
    )


@router.put("/me/password", status_code=204)
async def change_password(
    payload: ChangePasswordRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_auth_db),
):
    """Change the authenticated user's own password."""
    if not verify_password(payload.current_password, current_user.hashed_password):
        raise HTTPException(status_code=400, detail="Current password is incorrect")

    user = await db.get(User, current_user.id)
    user.hashed_password = hash_password(payload.new_password)
    user.must_change_pw  = False
    await db.commit()


@router.post("/reset-password/confirm", status_code=204)
async def confirm_reset_password(
    payload: ResetPasswordConfirmRequest,
    db: AsyncSession = Depends(get_auth_db),
):
    """Set a new password using a one-time reset token generated by an admin."""
    result = await db.execute(
        select(PasswordResetToken).where(PasswordResetToken.token == payload.token)
    )
    reset_token = result.scalar_one_or_none()

    if not reset_token:
        raise HTTPException(status_code=400, detail="Invalid reset token")
    if reset_token.used:
        raise HTTPException(status_code=400, detail="Reset token already used")
    if reset_token.expires_at < datetime.now(timezone.utc):
        raise HTTPException(status_code=400, detail="Reset token has expired")

    user = await db.get(User, reset_token.user_id)
    if not user or not user.is_active:
        raise HTTPException(status_code=400, detail="User not found or inactive")

    user.hashed_password = hash_password(payload.new_password)
    user.must_change_pw  = False
    reset_token.used     = True
    await db.commit()
