name: Deploy to Hetzner

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # It allows you to run it manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Hetzner via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: 22
          script: |
            cd /opt/lip2   # ← Change this route to the actual one on your server.
            git pull origin main
            docker compose down
            docker compose up --build -d
            echo "✅ Deploy completado correctamente"

